### ISSUE TITLE
seems like keyframes are broken

### ISSUE THREAD

**Issue by orouz** [vkalinichev/postcss-rtl#1] opened 2016-10-29 15:15 UTC
great plugin! thanks! 

seems like prepending `html[dir]` before each step of the keyframes is not valid

here's a codepen to illustrate the problem 
http://codepen.io/orouz/pen/NRZxBN

i think duplicating the whole keyframes while adjusting the animation name (and keyframes' properties) to correspond to the direction is a possible solution. what do you think?

**Comment by vkalinichev** [comment] 2016-10-29 18:00
Yes, I had planned to do it right this way

**Comment by vkalinichev** [comment] 2016-10-29 18:31
Fixed in 0.3.0: implemented separation for @keyframes with -rtl and -rtl postfixes.

**Closed by vkalinichev** 2016-10-29 18:31 UTC
Labels: bug, enhancement

**Comment by orouz** [comment] 2016-10-30 02:32
hey, thanks for the quick update! 

i ran into a new issue after upgrading that seems related, downgrading fixed it. 
i'm using react-toolbox and my build fails to compile 2 `.scss` files with keyframes in them. [#1](https://github.com/react-toolbox/react-toolbox/blob/dev/lib/checkbox/theme.scss) [#2](https://github.com/react-toolbox/react-toolbox/blob/dev/lib/progress_bar/theme.scss) 

this is the error:
```
Module build failed: TypeError: Cannot read property 'replace' of undefined
```
the stack trace goes through 2 files besides the `scss`. the first is `node_modules/postcss-advanced-variables/index.js` and the second is `node_modules/postcss/lib/lazy-result.js`

and my webpack config looks like this:

```
       {
         test: /\.(css|scss)$/,
         loaders: ['style', 'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',  'postcss', 'sass']
        },
```

not sure if i'm doing something wrong or that there is indeed an issue. could you clarify?

**Comment by vkalinichev** [comment] 2016-10-31 19:38
I cannot reproduce your errors: react-toolbox with your webpack.config works fine to me: both checkbox and progress-bar animations are works.

Anyway, I fully refactor `@keyframes` processing part, if you get any errors, please create new issue.

Thanks.

**Comment by orouz** [comment] 2016-11-01 22:29
the issue is sorted now. thank you for your work! greatly appreciated!
